# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '164a874a-09f1-4ee7-a082-bc8a980dc624'
  imageRepository: 'piholeunbound'
  containerRegistry: 'lygris.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


steps:
- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: 'Docker Hub'
    command: login
- script: |
   docker run --privileged --rm tonistiigi/binfmt --install arm64
         docker run --privileged --rm tonistiigi/binfmt
         docker buildx create --use
         docker buildx build --platform linux/amd64,linux/arm64 \
           -t lygris/pihole-unbound:$(build.buildNumber) \
           -t lygris/pihole-unbound:latest \
           --push \
           .
  displayName: 'Docker build arm64'