# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: ghcr.io/lygris/pihole-unbound:latest
    hostname: pihole
    environment:
      FTLCONF_LOCAL_IPV4: 172.16.0.2
      # set a secure password here or the default will be firewalla
      WEBPASSWORD: 'firewalla'
    # Volumes store your data between container upgrades
    volumes:
      - '/data/pi-hole/etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    networks:
      default:
        # static IP address for pi-hole
        ipv4_address: 172.16.0.2
        ipv6_address: fc00::2
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
     config:
       # your chosen docker network here
       - subnet: 172.16.0.0/24
       - subnet: fc00::/7